// <auto-generated />
using System;
using MealPlannerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPlannerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403151648_FoodUserKeyAdded")]
    partial class FoodUserKeyAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPlannerApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Snídaně"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Oběd"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Večeře"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Svačina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Slané"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sladké"
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.DayMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<int?>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("DayMeals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayId = 1,
                            FoodId = 1,
                            MealId = 1,
                            Time = new TimeSpan(0, 8, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Creator")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Difficulty")
                        .HasColumnType("numeric");

                    b.Property<bool?>("HasCustomNutrition")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("NutritionId")
                        .HasColumnType("integer");

                    b.Property<int>("PortionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Recipe")
                        .HasMaxLength(10000)
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutritionId");

                    b.HasIndex("UserId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 5m,
                            Confirmed = true,
                            Creator = "Luky",
                            Difficulty = 1m,
                            HasCustomNutrition = true,
                            IsPublic = true,
                            Name = "Míchaná vajíčka na másle",
                            NutritionId = 6,
                            PortionCount = 1,
                            Recipe = "Rozpusťte máslo, přidejte vejce rozšlehaná s mlékem a pomalu míchejte do ztuhnutí. Podávejte s chlebem. Recept pro 1 osobu.",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            FoodId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            FoodId = 1
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.FoodIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitId");

                    b.ToTable("FoodIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 4m,
                            FoodId = 1,
                            IngredientId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10m,
                            FoodId = 1,
                            IngredientId = 2,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50m,
                            FoodId = 1,
                            IngredientId = 4,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("NutritionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutritionId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vejce",
                            NutritionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Máslo",
                            NutritionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chléb",
                            NutritionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mléko",
                            NutritionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Šunka",
                            NutritionId = 5
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Snídaně"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Oběd"
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.Nutrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Kcal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Protein")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Sacharid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Nutritions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fat = 11m,
                            Kcal = 155m,
                            Protein = 13m,
                            Sacharid = 1.1m
                        },
                        new
                        {
                            Id = 2,
                            Fat = 81m,
                            Kcal = 717m,
                            Protein = 0.8m,
                            Sacharid = 0.1m
                        },
                        new
                        {
                            Id = 3,
                            Fat = 1m,
                            Kcal = 250m,
                            Protein = 9m,
                            Sacharid = 48m
                        },
                        new
                        {
                            Id = 4,
                            Fat = 1.5m,
                            Kcal = 42m,
                            Protein = 3.4m,
                            Sacharid = 5m
                        },
                        new
                        {
                            Id = 5,
                            Fat = 6m,
                            Kcal = 145m,
                            Protein = 21m,
                            Sacharid = 1m
                        },
                        new
                        {
                            Id = 6,
                            Fat = 30.85m,
                            Kcal = 402.7m,
                            Protein = 27.78m,
                            Sacharid = 4.71m
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "g"
                        },
                        new
                        {
                            Id = 2,
                            Type = "ml"
                        },
                        new
                        {
                            Id = 3,
                            Type = "ks"
                        },
                        new
                        {
                            Id = 4,
                            Type = "kg"
                        },
                        new
                        {
                            Id = 5,
                            Type = "l"
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "LB@example.com",
                            FName = "L",
                            LName = "B",
                            PasswordHash = "placeholder_hash",
                            Role = "Admin",
                            Username = "LB"
                        });
                });

            modelBuilder.Entity("MealPlannerApi.Models.Day", b =>
                {
                    b.HasOne("MealPlannerApi.Models.User", "User")
                        .WithMany("Days")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApi.Models.DayMeal", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Day", "Day")
                        .WithMany("DayMeals")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.Food", "Food")
                        .WithMany("DayMeals")
                        .HasForeignKey("FoodId");

                    b.HasOne("MealPlannerApi.Models.Meal", "Meal")
                        .WithMany("DayMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Food", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Nutrition", "Nutrition")
                        .WithMany()
                        .HasForeignKey("NutritionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlannerApi.Models.User", "User")
                        .WithMany("Foods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Nutrition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApi.Models.FoodCategory", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Food", null)
                        .WithMany("FoodCategories")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealPlannerApi.Models.FoodIngredient", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Food", "Food")
                        .WithMany("FoodIngredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.Ingredient", "Ingredient")
                        .WithMany("FoodIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.Unit", "Unit")
                        .WithMany("FoodIngredients")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Ingredient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Ingredient", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Nutrition", "Nutrition")
                        .WithMany()
                        .HasForeignKey("NutritionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Nutrition");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Rating", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Food", "Food")
                        .WithMany("Ratings")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Day", b =>
                {
                    b.Navigation("DayMeals");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Food", b =>
                {
                    b.Navigation("DayMeals");

                    b.Navigation("FoodCategories");

                    b.Navigation("FoodIngredients");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Ingredient", b =>
                {
                    b.Navigation("FoodIngredients");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Meal", b =>
                {
                    b.Navigation("DayMeals");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Unit", b =>
                {
                    b.Navigation("FoodIngredients");
                });

            modelBuilder.Entity("MealPlannerApi.Models.User", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Foods");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
